name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Установка Flutter SDK
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest' # Можно указать конкретную версию, если нужно

      - name: Install dependencies
        run: flutter pub get

      # Проверка форматирования (раскомментируйте, если нужно)
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      # Анализ кода с помощью Flutter
      - name: Analyze project source
        run: flutter analyze

      # Запуск тестов для Flutter проекта
      - name: Run tests
        run: flutter test
